apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuario-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuario-service
  template:
    metadata:
      labels:
        app: usuario-service
    spec:
      containers:
        - name: usuario-service
          image: richyortega/usuario-service:v6
          ports:
            - containerPort: 5080
          env:
            - name: APP_PORT
              value: '5080'
            - name: MONGO_URI
              value: 'mongodb://admin:admin123@mongodb:27017/usuario?authSource=admin'
#            - name: MONGO_USER
#              value: admin
#            - name: MONGO_PASS
#              value: admin123
#            - name: MONGO_HOST
#              value: mongodb
#            - name: MONGO_PORT
#              value: '27017'
#            - name: MONGO_DB
#              value: usuario
